# -*- coding: utf-8 -*-
"""while_loop_practice_v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WlkbrNv9o5e9TrSWx9cqFUjWA4ml458Y

Q1. Print numbers from 1 to 20 using while loop.

Approach:
- Initialize a variable
- Use while condition
- Increment inside loop
"""

#write answer here
x=1
while x<=20:
  print(x)
  x+=1

"""Q2. Print even numbers till 50 using while loop.

Approach:
- Start from 2
- Increment by 2
- Stop at 50
"""

#write answer here
a=2
while a<=50:
  print(a)
  a+=2

"""Q3. Print multiplication table of 5.

Approach:
- Initialize counter
- Multiply inside loop
"""

#write answer here
x=5
num=1
while num<=10:
  result = x*num
  print(f"{x} * {num} = {x*num}")
  num+=1

"""Q4. Find sum of numbers from 1 to n.

Approach:
- Take input n
- Add numbers in loop
"""

#write answer here
n = int(input("Enter a number :"))
sum = 0
while n!=0:
  sum+=n
  n = int(input("Enter a number :"))
print("Sum=", sum)

"""Q5. Reverse a number using while loop.

Approach:
- Extract last digit
- Build reversed number
"""

#write answer here
num = int(input("Enter a number: "))
a = 1
while a<=num:
  if a%4 == 0:
    a+=1
    continue
  print(a)
  a+=1

"""Q6. Count digits in a number.

Approach:
- Divide number by 10 repeatedly
- Count iterations
"""

#write answer here
n = int(input("Enter a number :"))
count = 0
while n!=0:
  n//=10
  count+=1
print("Number of digits=", count)

"""Q7. Check if a number is palindrome.

Approach:
- Reverse number
- Compare with original
"""

#write answer here
n = int(input("Enter a number: "))
original = n
reverse = 0

while n != 0:
    digit = n % 10
    reverse = reverse * 10 + digit
    n = n // 10

if original == reverse:
    print("Palindrome number")
else:
    print("Not a palindrome number")

"""Q8. Guess the number game.

Approach:
- Use while loop
- Continue until correct guess
"""

#write answer here
guess_num = 10
user_number = int(input("Enter a guess number: "))

while user_number != guess_num:
    if user_number > guess_num:
        print("Too High")
    else:
        print("Too Low")

    user_number = int(input("Enter a guess number: "))

print("Correct number 🎉")

"""Submission link for this assignment -"""